### ISSUE TITLE
ECS.1 Control check confusing

### ISSUE THREAD

**Issue by lobobinario** [awsdocs/aws-security-hub-user-guide#10]
This controls says:
_This control checks whether an active Amazon ECS task definition that has host networking mode also has privileged or user container definitions. The control fails for task definitions that have host network mode and container definitions where **privileged=false** or is empty and user=root or is empty._

I think the control should look for privileged=true instead of privileged=false

**Comment by jmanwiller** [comment]
Checking with the controls team. Apologies for the delayed response - was out of the office.

**Comment by jmanwiller** [comment]
Finally received an answer from the controls team. Apologies again for the delayed response.

Per the controls team, the check for **privileged=false** is correct. The check is looking for an escalation of privilege that is unintentional. If **privileged=true**, then that is intentional.

Their response:

This control checks for unexpected privilege escalation when a task definition has host networking enabled but the customer has not opted in to elevated privileges. Not opting into elevated privileges is signaled by specifying setting **privileged** to **false**.

**Comment by lobobinario** [comment]
Ok, cool. That clarification makes understanding the control better. Thanks
